name: Horusec

on:
  pull_request:
    branches: [ "**" ]

jobs:
  horusec-security:
    name: horusec-security
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0
      - name: Running Horusec Security Download latest version
        shell: bash
        run: |
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest-rc
          horusec start -p . -e